#!/usr/bin/env bash
# Compiles baseline + each role guide into self-contained bundles in dist/.
# Edit source in baseline/ and guides/, never dist/. Run this after every edit.
set -euo pipefail
cd "$(dirname "$0")"

BASELINE="baseline/FIRMWIDE_BASELINE.md"
[ -f "$BASELINE" ] || { echo "ERROR: $BASELINE not found" >&2; exit 1; }

VERSION=$(grep -m1 '^Version:' "$BASELINE" | awk '{print $2}')
mkdir -p dist

for guide in guides/*.md; do
  name=$(basename "$guide")
  {
    echo "<!-- GENERATED by build.sh — do not edit."
    echo "     Source: $BASELINE (v${VERSION}) + $guide"
    echo "     This file is self-contained: baseline + role guide. Distribute this one. -->"
    echo
    cat "$BASELINE"
    echo
    echo "---"
    echo
    cat "$guide"
  } > "dist/$name"
  echo "built dist/$name"
done

echo "OK: $(ls dist/*.md | wc -l | tr -d ' ') bundles (baseline v${VERSION})"
